config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: {sign_in: 'login', sign_out: 'logout', sign_up: 'register'}
  resources :portfolios, except: [:show] do
    put :sort, on: :collection
  end
  get 'portfolios/:id', to: 'portfolios#show', as: 'portfolio_show'

  get 'about', to: 'pages#about'
  get 'contact', to: 'pages#contact'
  get 'tech-news', to: 'pages#tech_news'

  resources :blogs do
    member do
      get :toggle_status
    end
  end

  mount ActionCable.server => '/cable'

  root to: 'pages#home'
end

app/models/blog.rb
class Blog < ApplicationRecord
  enum status: { draft: 0, published: 1}
  extend FriendlyId
  friendly_id :title, use: :slugged
  
  validates_presence_of :title, :body

  #belongs_to :topic
  
  has_many :comments, dependent: :destroy

  def self.special_blogs
    all
  end

  def self.featured_blogs
    limit(2)
  end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:show, :edit, :update, :destroy, :toggle_status]
  layout "blog"
  access all: [:show, :index], user: {except: [:destroy, :new, :create, :update, :edit, :toggle_status]}, site_admin: :all

  # GET /blogs
  # GET /blogs.json
  def index
    if logged_in?(:site_admin)
      @blogs = Blog.order(id: :desc).page(params[:page]).per(5)
      @page_title = "Blog"
    else
      @blogs = Blog.order(id: :desc).page(params[:page]).per(5).published
      @page_title = "Blog"
    end
  end

  # GET /blogs/1
  # GET /blogs/1.json
  def show
    if logged_in?(:site_admin) || @blog.published?
      @blog = Blog.includes(:comments).friendly.find(params[:id])
      @comment = Comment.new

      @page_title = @blog.title
    else
      redirect_to blogs_path, notice: "You are not authorized to access this page"
    end
  end

  # GET /blogs/new
  def new
    @blog = Blog.new
  end

  # GET /blogs/1/edit
  def edit
  end

  # POST /blogs
  # POST /blogs.json
  def create
    @blog = Blog.new(blog_params)

    respond_to do |format|
      if @blog.save
        format.html { redirect_to @blog, notice: 'Your post is now live.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /blogs/1
  # PATCH/PUT /blogs/1.json
  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to @blog, notice: 'Your updates are now live.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /blogs/1
  # DELETE /blogs/1.json
  def destroy
    @blog.destroy
    respond_to do |format|
      format.html { redirect_to blogs_url, notice: 'Blog was successfully destroyed.' }
    end
  end

  def toggle_status
    if @blog.draft?
      @blog.published!
    elsif @blog.published?
      @blog.draft!
    end
    redirect_to blogs_url, notice: 'Post status updated.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = Blog.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def blog_params
      params.require(:blog).permit(:title, :body)
    end
end

app/helpers/blogs_helper.rb
module BlogsHelper
  def gravatar_helper user
   image_tag "https://www.gravatar.com/avatar/#{Digest::MD5.hexdigest(user.email)}", width: 40
  end
end

app/views/blogs/_blog.html.erb
  <div class="blog-post">
    <h2 class="blog-post-title">
      <%= link_to blog.title, blog %>
    </h2>
    <p class="blog-post-meta">
      Published <%= distance_of_time_in_words(blog.created_at, Time.now) %> ago
    </p>
    <% if logged_in?(:site_admin) %>
      <p class="blog-post-meta">
        <%= link_to blog.status, toggle_status_blog_path(blog) %> |
        <%= link_to 'Edit', edit_blog_path(blog) %> |
        <%= link_to 'Delete Post', blog, method: :delete, data: { confirm: 'Are you sure?' } %>
      </p>
    <% end %>  
    
      <%= blog.body %>
      <br />
      <br />
      <br />
      <br />
  </div>

app/views/blogs/_form.html.erb
<%= form_with(model: blog, local: true) do |form| %>
  <% if blog.errors.any? %>
    <% blog.errors.full_messages.each do |error| %>
      <%= js add_gritter(error, title: "Stephen Swann's Blog", sticky: false) %>
    <% end %>
  <% end %>

  <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title, id: :blog_title, class:'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :body %>
    <%= form.text_area :body, id: :blog_body, class:'form-control', rows: 15 %>
  </div>

  <div class="actions">
    <%= form.submit "Submit", class: 'btn btn-success' %>
  </div>
<% end %>

app/views/blogs/edit.html.erb
<h1>Editing Blog</h1>

<%= render 'form', blog: @blog %>

<%= link_to 'Show', @blog %> |
<%= link_to 'Back', blogs_path %>

app/views/blogs/index.html.erb
  <%= paginate @blogs %>
  
  <%= link_to 'New Blog', new_blog_path if logged_in?(:site_admin) %>

  <%= render @blogs %>

  <%= paginate @blogs %>

app/views/blogs/new.html.erb
<h1>New Blog</h1>

<%= render 'form', blog: @blog %>

<%= link_to 'Back', blogs_path %>

app/views/blogs/show.html.erb
  <div class="blog-post">
    <h2 class="blog-post-title">
      <%= @blog.title %>
    </h2>

    <%= @blog.body %>
  </div>

<% if logged_in?(:site_admin) %>
  <%= link_to 'Edit', edit_blog_path(@blog)  %> |
<% end %>
<%= link_to 'Back', blogs_path, class:'btn btn-outline-primary' %>

<%= render 'comments/comment_form' %>
<div id="comments" data-blog-id="<%= @blog.id %>">
  <%= render @blog.comments %>
</div>