config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: {sign_in: 'login', sign_out: 'logout', sign_up: 'register'}
  resources :portfolios, except: [:show] do
    put :sort, on: :collection
  end
  get 'portfolios/:id', to: 'portfolios#show', as: 'portfolio_show'

  get 'about', to: 'pages#about'
  get 'contact', to: 'pages#contact'
  get 'tech-news', to: 'pages#tech_news'

  resources :blogs do
    member do
      get :toggle_status
    end
  end

  mount ActionCable.server => '/cable'

  root to: 'pages#home'
end

app/models/portfolio.rb
class Portfolio < ApplicationRecord
  has_many :technologies, dependent: :destroy
  accepts_nested_attributes_for :technologies,
                                reject_if: lambda { |attrs| attrs['name'].blank? },
                                allow_destroy: true


  validates_presence_of :title, :body

  mount_uploader :thumb_image, PortfolioUploader
  mount_uploader :main_image, PortfolioUploader


  # Does the same thing as scope but not a best practice.
  def self.angular
    where(subtitle: "Angular")
  end

  # Considered a best practice
  scope :ruby_on_rails_portfolio_items, -> { where(subtitle: "Ruby on Rails") }

  def self.by_position
    self.order("position ASC")
  end
end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController
  before_action :set_portfolio, only:[:edit, :show, :update, :destroy]
  layout "portfolio"
  access all: [:show, :index], user: {except: [:destroy, :new, :create, :update, :edit, :sort]}, site_admin: :all


  def index
    @portfolio_item = Portfolio.by_position
    # @portfolio_item = Portfolio.includes(:technologies)
  end

  def sort
    params[:order].each do |key, value|
      Portfolio.find(value[:id]).update(position: value[:position])
    end

    render nothing: true
  end

  def show
  end

  def new
    @portfolio_item = Portfolio.new
  end

  def edit
  end

  def create
    @portfolio_item = Portfolio.new(portfolio_params)
    respond_to do |format|
      if @portfolio_item.save
        format.html { redirect_to portfolios_path, notice: "Your post is now live." }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @portfolio_item.update(portfolio_params)
        format.html {redirect_to portfolio_path, notice: 'Your updates are live.'}
      else
        format.html {render :edit }
      end
    end
  end

  def destroy
    @portfolio_item.destroy
    respond_to do |format|
      format.html {redirect_to portfolios_path, notice: "The Portfolio Item was destroyed."}
    end
  end

  private
    def set_portfolio
      @portfolio_item = Portfolio.find(params[:id])
    end

    def portfolio_params
      params.require(:portfolio).permit(:title,
                                        :subtitle,
                                        :body,
                                        :main_image,
                                        :thumb_image,
                                        technologies_attributes: [:id, :name, :_destroy]
                                        )
    end
end

app/helpers/portfolios_helper.rb
module PortfoliosHelper
  def image_generator(height:, width:)
    "http://placehold.it/#{height}x#{width}"
  end
end

app/views/portfolios/_form.html.erb
<%= form_for @portfolio_item do |form| %>
  <% if @portfolio_item.errors.any? %>
    <% @portfolio_item.errors.full_messages.each do |error| %>
      <%= js add_gritter(error, title: "Stephen Swann's Blog", sticky: false) %>
    <% end %>
  <% end %>
  <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title, class:'form-control'%>
  </div>

  <div class="form-group">
    <%= form.label :subtitle %>
    <%= form.text_area :subtitle, class:'form-control'%>
  </div>

  <div class="form-group">
   <label class="btn btn-primary">
     Upload thumbnail image file <%= form.file_field :thumb_image, style:'display:none;' %>
   </label>
  </div>
  
  <div class="form-group">
   <label class="btn btn-primary">
     Upload main image file <%= form.file_field :main_image, style:'display:none;' %>
   </label>
  </div>

  <div class="form-group">
    <%= form.label :body %>
    <%= form.text_area :body, class:'form-control', rows:7 %>
  </div>

  <div class="form-group">
    <%= form.fields_for :technologies, class:'form-control' do |technology_form| %>
      <%= render 'technology_fields', :form => technology_form %>
    <% end%>
    <%= link_to_add_association 'Add Technology', form, :technologies, form_name: 'form', class:'btn btn-success' %>
  </div>

  <div class="actions">
    <%= form.submit "Submit", class:'btn btn-outline-success' %>
  </div>
<% end %>

app/views/portfolios/_portfolio_item.html.erb
<div class="col-md-4">
  <div class="card mb-4" data-id="<%= portfolio_item.id %>">
      <%= link_to portfolio_show_path(portfolio_item) do %>
        <%= image_tag portfolio_item.thumb_image, class:'card-img-top' unless portfolio_item.thumb_image.nil? %>
      <% end %>
    <div class="card-body">
      <%= link_to portfolio_item.title, portfolio_show_path(portfolio_item) %>
      <%= portfolio_item.subtitle %>
      <div class="btn-group">
      <% if logged_in?(:site_admin) %>
        <%= link_to 'Edit', edit_portfolio_path(portfolio_item), class:'btn btn-sm btn-outline-warning'  %>
        <%= link_to 'Delete', portfolio_path(portfolio_item), class:'btn btn-sm btn-outline-danger', method: :delete, data: {
        confirm: 'Are you sure?' }  %>
      <% end %>
      </div>
    </div>
  </div>
</div>

app/views/portfolios/_technology_fields.html.erb
<div class="nested-fields">
  <div class="field">
  <%= form.label :name, 'Technology' %>
  <%= form.text_field :name, class:'form-control' %>
  </div>
<%= link_to_remove_association "Remove Technology", form, class:'btn btn-danger' %>
</div>

app/views/portfolios/edit.html.erb
<div class="container">
  <div class="row">
  
    <div class="col-md-4">
      <h1>Edit a Portfolio Item</h1> 
    </div>
    <div class="col-md-6">
      <%= render 'form', portfolio_item: @portfolio_item %>
    </div>
    <div class="col-md-4"></div>
  </div>
</div>

app/views/portfolios/index.html.erb
<span class="float-right">
  <%= link_to 'Create New Item', new_portfolio_path, class:'btn btn-outline-success' if logged_in?(:site_admin) %>
</span>
<div class="album py-5 bg-light">
  <div class="container">
    <div class="row  <%= "sortable" if logged_in?(:site_admin) %>">
      <%= render partial: 'portfolio_item', collection: @portfolio_item %>
    </div>
  </div>
</div>

app/views/portfolios/new.html.erb
<div class="container">
  <div class="row">
  
    <div class="col-md-4">
      <h1>Create new Portfolio Item</h1> 
    </div>
    <div class="col-md-6">
      <%= render 'form', portfolio_item: @portfolio_item %>
    </div>
    <div class="col-md-4"></div>
  </div>
</div>

app/views/portfolios/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-7">
      <%= image_tag @portfolio_item.main_image, width:'100%' %>
    </div>
    <div class="col-md-5">
      <h1><%= @portfolio_item.title %></h1>

      <em><%= @portfolio_item.subtitle %></em>

      <p><%= @portfolio_item.body %></p>

      <h2>Technologies Used:</h2>

      <% @portfolio_item.technologies.each do |t| %>
        <p><%= t.name %></p>
      <% end %>
      <% if logged_in?(:site_admin) %>
        <%= link_to 'Edit', edit_portfolio_path, class:'btn btn-sm btn-outline-warning'  %>
        <%= link_to 'Delete', portfolio_path, class:'btn btn-sm btn-outline-danger', method: :delete, data: { confirm: 'Are you sure?' } %>
      <% end %>
    </div>
  </div>
</div>