config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: {sign_in: 'login', sign_out: 'logout', sign_up: 'register'}
  resources :portfolios, except: [:show] do
    put :sort, on: :collection
  end
  get 'portfolios/:id', to: 'portfolios#show', as: 'portfolio_show'

  get 'about', to: 'pages#about'
  get 'contact', to: 'pages#contact'
  get 'tech-news', to: 'pages#tech_news'

  resources :blogs do
    member do
      get :toggle_status
    end
  end

  mount ActionCable.server => '/cable'

  root to: 'pages#home'
end

app/views/shared/_alerts.html.erb
<% if flash[:alert] %>
  <%= js add_gritter(flash[:flash], title: "Stephen Swann's Portfolio", sticky: false)  %>
<% elsif flash[:error] %>
  <%= js add_gritter(flash[:error], title: "Stephen Swann's Portfolio", sticky: false) %>
<% else %>
  <%= js add_gritter(flash[:notice], title: "Stephen Swann's Portfolio", sticky: false) %>
<% end %>

app/views/shared/_application_footer.html.erb
<footer class="mastfoot mt-auto">
  <div class="inner">
    <p class="app-footer">
      <%= copyright_generator %>
    </p>
  </div>
</footer>

app/views/shared/_application_nav.html.erb
<div class="masthead mb-auto">
	<div class="inner">
		<h3 class="masthead-brand">Stephen Swann</h3>
		<nav class="nav nav-masthead justify-content-center app-nav">
      <%= nav_helper 'nav-link', 'span' %>
      <%= login_helper 'nav-link' %>
		</nav>
	</div>
</div>

app/views/shared/_blog_footer.html.erb
    <footer class="blog-footer">
      <%= copyright_generator %>
      <br />
      <a href="#">
        <%= fa_icon "arrow-up 3x" %>
        <br />
        To the top
      </a>
    </footer>

app/views/shared/_blog_header.html.erb
 <header class="blog-header py-3">
  <div class="row flex-nowrap justify-content-between align-items-center">
    <div class="col-4 pt-1">
      <a class="text-muted" href="#">Subscribe</a>
    </div>
    <div class="col-4 text-center">
      <a class="blog-header-logo text-dark" href="#">Stephen's Blog</a>
    </div>
    <div class="col-4 d-flex justify-content-end align-items-center">
      <%= login_helper "btn btn-sm btn-outline-secondary" %>
    </div>
  </div>
 </header>

app/views/shared/_blog_nav.html.erb
<div class="nav-scroller py-1 mb-2">
  <nav class="nav d-flex justify-content-between">
    <%= nav_helper 'p-2 text-muted', 'div' %>
  </nav>
</div>

app/views/shared/_blog_sidebar.html.erb
 <aside class="col-md-4 blog-sidebar">
   <div class="p-3 mb-3 bg-light rounded">
     <h4 class="font-italic">About </h4>
     <p class="mb-0">I am an application developer specializing in Ruby on Rails and Angular.  I am available to start on new projects so feel free to reach out to me by phone or email.</p>
   </div>

   <div class="p-3">
     <h4 class="font-italic">I am elsewhere, also</h4>
     <ol class="list-unstyled">
       <li><a href="https://bitbucket.org/scswan85"><%= fa_icon "bitbucket 3x" %></a></li>
       <li><a href="https://www.instagram.com/stephenswann"><%= fa_icon "instagram 3x" %></a></li>
       <li><a href=""></a></li>
     </ol>
   </div>
 </aside>

app/views/shared/_nav.html.erb
<div class="<%= location %>">
  <%= nav_helper '', 'div' %>
</div>

app/views/shared/_portfolio_footer.html.erb
<footer class="text-muted">
  <div class="container">
    <div class="float-right">
    
    <% if params[:action] == 'show' or 'new' or 'edit' %>
      <%= link_to (fa_icon "folder-open 2x"), portfolios_path %>
      <%= link_to "Back to Portfolio", portfolios_path %>
    <% end %>
    <%= link_to (fa_icon "arrow-circle-up 2x"), "#" %>
    <%= link_to "Top of top (of the page)!", "#" %>
    </div>
    <%= copyright_generator %>
  </div>
</footer>

app/views/shared/_portfolio_main.html.erb
<main role="main">
  <section class="jumbotron text-center">
   <div class="container">
     <h1 class="jumbotron-heading">My Portfolio</h1>
     <p class="navbar text-muted">Welcome to my portfolio. Below you can see some of my recent projects.  Please reach out to me with any questions.</p>
      <%= link_to "Contact Me", contact_path, class:"btn btn-primary my-2" %>
      <%= link_to "About Me", about_path, class:"btn btn-secondary my-2" %>
   </div>
  </section>
</main>

app/views/shared/_portfolio_nav.html.erb
<header>
  <div class="collapse bg-dark" id="navbarHeader">
    <div class="container">
      <div class="row">
        <div class="col-sm-8 col-md-7 py-4">
          <h4 class="text-white">About</h4>
          <p class="text-muted">This is where you can see my more recent projects and get an idea of what I have been up to.  As always feel free to contact me with any questions</p>
        </div>
        <div class="col-sm-4 offset-md-1 py-4">
          <h4 class="text-white">Look around</h4>
          <ul class="list-unstyled">
            <%= nav_helper '', 'li' %>
            <li><%= login_helper_vertical %></li>
          </ul>
        </div>
      </div>
    </div>
  </div>
  <div class="navbar navbar-dark bg-dark box-shadow">
    <div class="container d-flex justify-content-between">
      <%= link_to "Stephen Swann", portfolios_path, class:'navbar-brand d-flex align-items-center' %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
    </div>
  </div>
</header>